In [1]:
#SOURCE:: https://www.datacamp.com/community/tutorials/deep-learning-python

# Import libraries 
import pandas as pd
import numpy as np
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix

from keras.models import Sequential
from keras.layers.core import Dense, Activation
from keras.optimizers import SGD,RMSprop

Using TensorFlow backend.


In [2]:
# Read in white wine data 
white = pd.read_csv("http://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-white.csv", sep=';')
# Read in red wine data 
red = pd.read_csv("http://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv", sep=';')
#append
wines = red.append(white, ignore_index=True)

In [3]:
X = wines.drop('quality', axis = 1)
y = wines.quality
X.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  
0      9.4  
1      9.8  
2      9.8  
3      9.8  
4      9.4

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [5]:
#preprocess data
X_train = StandardScaler().fit_transform(X_train)

X_test = StandardScaler().fit_transform(X_test)

In [6]:
#Initialize the models
model = Sequential()

model.add(Dense(128, activation = 'relu', input_shape = (11,)))
model.add(Dense(128, activation = 'relu'))
model.add(Dense(64, activation = 'relu'))
model.add(Dense(1))

In [7]:
model.compile(optimizer='rmsprop',
             loss = 'mse',
             metrics = ['mae'])

In [8]:
model.fit(X_train, y_train, epochs = 10, verbose = 1)

Epoch 1/10
4352/4352 [==============================] - 0s 48us/step - loss: 2.9251 - mean_absolute_error: 1.2364
Epoch 2/10
4352/4352 [==============================] - 0s 24us/step - loss: 0.9869 - mean_absolute_error: 0.7703
Epoch 3/10
4352/4352 [==============================] - 0s 24us/step - loss: 0.7019 - mean_absolute_error: 0.6548
Epoch 4/10
4352/4352 [==============================] - 0s 24us/step - loss: 0.6437 - mean_absolute_error: 0.6218
Epoch 5/10
4352/4352 [==============================] - 0s 23us/step - loss: 0.5814 - mean_absolute_error: 0.5938
Epoch 6/10
4352/4352 [==============================] - 0s 22us/step - loss: 0.5630 - mean_absolute_error: 0.5804
Epoch 7/10
4352/4352 [==============================] - 0s 23us/step - loss: 0.5416 - mean_absolute_error: 0.5704
Epoch 8/10
4352/4352 [==============================] - 0s 23us/step - loss: 0.5335 - mean_absolute_error: 0.5691
Epoch 9/10
4352/4352 [==============================] - 0s 25us/step - loss: 0.5242 - me

In [9]:
loss, accuracy = model.evaluate(X_test, y_test, verbose = 0)
print("Accuracy = {:.2f}".format(accuracy))

Accuracy = 0.58


In [10]:
Y_pred = model.predict(X_test)
print("Confusion Matrix:\n",confusion_matrix(y_test, Y_pred.round()))

Confusion Matrix:
 [[  0   0   3   5   2   0   0]
 [  0   1  35  39   1   0   0]
 [  0   2 237 404  28   1   0]
 [  0   0  85 673 210   9   0]
 [  0   0   0 133 213   6   0]
 [  0   0   0  10  42   5   0]
 [  0   0   0   0   1   0   0]]
